#!/bin/sh
set -u
set -x

killall hugo 2>&1
cd ../xaprb-web && git reset --hard HEAD && git checkout gh-pages
cd -
git add --all . && git commit -am "pending changes" && git push
hugo
cd -
git add --all . && git commit -am "render with hugo" && git push
